### ISSUE TITLE
Usage throws Mechanize "NoMethodError"

### ISSUE THREAD

**Issue by villasv** [kinduff/slack-big-emoji#1]
```
Traceback (most recent call last):
        8: from /home/villasv/.rbenv/versions/2.5.0/bin/slack-big-emoji:23:in `<main>'
        7: from /home/villasv/.rbenv/versions/2.5.0/bin/slack-big-emoji:23:in `load'
        6: from /home/villasv/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slack-big-emoji-0.1.0/bin/slack-big-emoji:41:in `<top (required)>'
        5: from /home/villasv/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slack-big-emoji-0.1.0/lib/slack_big_emoji/uploader.rb:17:in `upload_emojis'
        4: from /home/villasv/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slack-big-emoji-0.1.0/lib/slack_big_emoji/uploader.rb:42:in `move_to_emoji_page'
        3: from /home/villasv/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slack-big-emoji-0.1.0/lib/slack_big_emoji/uploader.rb:42:in `loop'
        2: from /home/villasv/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slack-big-emoji-0.1.0/lib/slack_big_emoji/uploader.rb:46:in `block in move_to_emoji_page'
        1: from /home/villasv/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/slack-big-emoji-0.1.0/lib/slack_big_emoji/uploader.rb:31:in `login'
/home/villasv/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/mechanize-2.7.5/lib/mechanize/form.rb:217:in `method_missing': undefined method `email=' for #<Mechanize::Form:0x00007fffe8da41a8> (NoMethodError)
```

**Comment by kinduff** [comment]
Thanks for reporting, I'll take a look

**Comment by ericgjerde** [comment]
Yeah, see the same error here... no dice.

**Comment by safaorhan** [comment]
Same problem..

**Comment by anitatse** [comment]
me too :(

**Comment by kinduff** [comment]
@anitatse @safaorhan @ericgjerde @villasv Really sorry about the delay, it's fixed now at version `0.1.1` https://rubygems.org/gems/slack-big-emoji/versions/0.1.1

**Comment by anitatse** [comment]
Thanks! The error is gone but it still doesn't seem to work correctly for me. For my one picture `jf.png`, it appears to save a single tile `jf%02d.png` into the folder named `jf`  and it does not appear to save to my team's slack workspace either. I'm using MacOS. 

```
$ slack-big-emoji jf.png
File Info
--------------
File name            jf
Ratio                1.0
File Resize Spec     640x640

Options
--------------
Tile Width           5
Crop Size            128x128

CLI Options
--------------
silent               false
convert_only         false
file                 jf.png

Converting
--------------
Temp Input           /var/folders/bz/3l4y88jx6zd32v5lnd0twflh0000gn/T/mini_magick20190320-30852-e78l1u.png
Output Dir           jf
Output Path          jf/jf%02d.png
Done                 Yes

Uploading
--------------
Your slack team name(subdomain): <team name>
Login email: <my email>
Login password(hidden): 
importing jf%02d...

Emoji Grid
--------------
:jf00::jf01::jf02::jf03::jf04:
:jf05::jf06::jf07::jf08::jf09:
:jf10::jf11::jf12::jf13::jf14:
:jf15::jf16::jf17::jf18::jf19:
:jf20::jf21::jf22::jf23::jf24:
```

**Comment by kinduff** [comment]
@anitatse Bummer! Can you post your OS and the output of `convert --version`?

**Comment by anitatse** [comment]
@kinduff  Currently using MacOS Sierra 10.12.6, and convert doesn't appear to be a command on my terminal `convert --version`. 

EDIT: Nevermind! Didn't realize ImageMagick wasn't properly installed on my system. Thanks and thanks for letting my slack workspace be memable 🤣

**Comment by kinduff** [comment]
@anitatse that's awesome! Thanks for letting me know, I will document clearly that imagemagick should be installed. Have fun!
